// scripts/embed-widget.mjs
// Inlines the built widget bundle (dist/mcp-app.html) into a TS module as a
// string constant, so the server (local Express or Vercel serverless) can
// import it directly instead of reading the file off disk at request time
// — the latter is fragile in a serverless bundle that doesn't statically
// trace fs.readFile calls.
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const inputPath = path.join(root, "dist", "mcp-app.html");
const outDir = path.join(root, "src", "generated");
const outPath = path.join(outDir, "widget-html.ts");

const html = fs.readFileSync(inputPath, "utf-8");
const escaped = html
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const out = `// Auto-generated by scripts/embed-widget.mjs from dist/mcp-app.html — do not edit by hand.
export const WIDGET_HTML = \`${escaped}\`;
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, out);
console.log(`Embedded ${inputPath} -> ${path.relative(root, outPath)}`);
